### ISSUE TITLE
Performance impact

### ISSUE THREAD

**Issue by rohitjoshi** [yzprofile/ngx_http_dyups_module#58]
Thanks for adding support to dynamically manipulate upstream backend config.
Is there any performance impact when Nginx is built with this module?  I see it's logging slot of data  on upstream every second.

**Comment by yzprofile** [comment]
Yes, There is an issue about performance, but not because of we logging upstream every second.

We do search upstream by name in the upstream list of nginx while a request coming in.

But the search algorithm is O(n), so we did a patch into Tengine, search upstream through rbtree https://github.com/alibaba/tengine/pull/367;

**Comment by rohitjoshi** [comment]
@yzprofile thanks.
